name: Sanity tests
on: [push, pull_request]
jobs:
  go-test:
    name: Go test and build
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v2
    - name: Checkout the branch
      uses: actions/checkout@v2
    - name: Go test
      run: make test
    - name: Go build
      run: make build
